export const generatedRoomIdls = {
  "canvas": {
    programName: "RoomCanvasClient",
    serviceName: "Room",
    idl: "\n!@sails: 1.0.1\n\nservice Room@0xf7b06275678f99bd {\n    events {\n        Closed,\n        Configured(u64),\n        Joined([u8; 32]),\n        Left([u8; 32]),\n        PixelPlaced {\n            x: u16,\n            y: u16,\n            color: u16,\n            who: [u8; 32],\n        },\n        Updated(u64),\n    }\n    functions {\n        CloseRoom() -> u64 throws RoomError;\n        Configure(config_blob: [u8]) -> u64 throws RoomError;\n        @query\n        Info() -> (String, u16, ActorId, u64, [u8]);\n        Join(name: String, kind: u16) -> u64 throws RoomError;\n        Leave() -> u64 throws RoomError;\n        @query\n        Participants() -> [(ActorId, String, u16, u64)];\n        PlacePixel(x: u16, y: u16, color: u16) -> u64 throws RoomError;\n        @query\n        Region(x: u16, y: u16, w: u16, h: u16) -> [u8] throws RoomError;\n        @query\n        Seq() -> u64;\n        @query\n        Since(from_seq: u64) -> (u64, [(u64, [u8])], bool);\n        @query\n        Snapshot() -> [u8];\n    }\n    types {\n        enum RoomError {\n            Closed,\n            NotOwner,\n            AlreadyJoined,\n            NotJoined,\n            NotAllowed,\n            ParticipantsFull,\n            NameTooLong {\n                max_bytes: u16,\n            },\n            PayloadTooLarge {\n                actual_bytes: u32,\n                max_bytes: u16,\n            },\n            RateLimited {\n                retry_after_secs: u32,\n            },\n            InvalidConfig,\n            InvalidKind,\n            InvalidBounds,\n            InvalidColor,\n            CooldownActive {\n                retry_after_secs: u32,\n            },\n        }\n    }\n}\n\nprogram RoomCanvasClient {\n    constructors {\n        Create(width: u16, height: u16, palette_size: u16, cooldown_secs: u16);\n    }\n    services {\n        Room@0xf7b06275678f99bd,\n    }\n}\n",
  },
} as const;

export type GeneratedRoomTemplate = keyof typeof generatedRoomIdls;
