// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct RoomCanvasClientProgram;

impl RoomCanvasClientProgram {
    pub const ROUTE_ID_ROOM: u8 = 1;
}

impl sails_rs::client::Program for RoomCanvasClientProgram {}

pub trait RoomCanvasClient {
    type Env: sails_rs::client::GearEnv;
    fn room(&self) -> sails_rs::client::Service<room::RoomImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> RoomCanvasClient
    for sails_rs::client::Actor<RoomCanvasClientProgram, E>
{
    type Env = E;
    fn room(&self) -> sails_rs::client::Service<room::RoomImpl, Self::Env> {
        self.service(RoomCanvasClientProgram::ROUTE_ID_ROOM)
    }
}
pub trait RoomCanvasClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        width: u16,
        height: u16,
        palette_size: u16,
        cooldown_secs: u16,
    ) -> sails_rs::client::PendingCtor<RoomCanvasClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> RoomCanvasClientCtors
    for sails_rs::client::Deployment<RoomCanvasClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        width: u16,
        height: u16,
        palette_size: u16,
        cooldown_secs: u16,
    ) -> sails_rs::client::PendingCtor<RoomCanvasClientProgram, io::Create, Self::Env> {
        self.pending_ctor((width, height, palette_size, cooldown_secs))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (width: u16, height: u16, palette_size: u16, cooldown_secs: u16) -> (), 0);
}

pub mod room {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum RoomError {
        Closed,
        NotOwner,
        AlreadyJoined,
        NotJoined,
        NotAllowed,
        ParticipantsFull,
        NameTooLong { max_bytes: u16 },
        PayloadTooLarge { actual_bytes: u32, max_bytes: u16 },
        RateLimited { retry_after_secs: u32 },
        InvalidConfig,
        InvalidKind,
        InvalidBounds,
        InvalidColor,
        CooldownActive { retry_after_secs: u32 },
    }

    pub trait Room {
        type Env: sails_rs::client::GearEnv;
        fn close_room(&mut self) -> sails_rs::client::PendingCall<io::CloseRoom, Self::Env>;
        fn configure(
            &mut self,
            config_blob: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::Configure, Self::Env>;
        fn info(&self) -> sails_rs::client::PendingCall<io::Info, Self::Env>;
        fn join(
            &mut self,
            name: String,
            kind: u16,
        ) -> sails_rs::client::PendingCall<io::Join, Self::Env>;
        fn leave(&mut self) -> sails_rs::client::PendingCall<io::Leave, Self::Env>;
        fn participants(&self) -> sails_rs::client::PendingCall<io::Participants, Self::Env>;
        fn place_pixel(
            &mut self,
            x: u16,
            y: u16,
            color: u16,
        ) -> sails_rs::client::PendingCall<io::PlacePixel, Self::Env>;
        fn region(
            &self,
            x: u16,
            y: u16,
            w: u16,
            h: u16,
        ) -> sails_rs::client::PendingCall<io::Region, Self::Env>;
        fn seq(&self) -> sails_rs::client::PendingCall<io::Seq, Self::Env>;
        fn since(&self, from_seq: u64) -> sails_rs::client::PendingCall<io::Since, Self::Env>;
        fn snapshot(&self) -> sails_rs::client::PendingCall<io::Snapshot, Self::Env>;
    }

    pub struct RoomImpl;

    impl sails_rs::client::Identifiable for RoomImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([247, 176, 98, 117, 103, 143, 153, 189]);
    }

    impl<E: sails_rs::client::GearEnv> Room for sails_rs::client::Service<RoomImpl, E> {
        type Env = E;
        fn close_room(&mut self) -> sails_rs::client::PendingCall<io::CloseRoom, Self::Env> {
            self.pending_call(())
        }
        fn configure(
            &mut self,
            config_blob: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::Configure, Self::Env> {
            self.pending_call((config_blob,))
        }
        fn info(&self) -> sails_rs::client::PendingCall<io::Info, Self::Env> {
            self.pending_call(())
        }
        fn join(
            &mut self,
            name: String,
            kind: u16,
        ) -> sails_rs::client::PendingCall<io::Join, Self::Env> {
            self.pending_call((name, kind))
        }
        fn leave(&mut self) -> sails_rs::client::PendingCall<io::Leave, Self::Env> {
            self.pending_call(())
        }
        fn participants(&self) -> sails_rs::client::PendingCall<io::Participants, Self::Env> {
            self.pending_call(())
        }
        fn place_pixel(
            &mut self,
            x: u16,
            y: u16,
            color: u16,
        ) -> sails_rs::client::PendingCall<io::PlacePixel, Self::Env> {
            self.pending_call((x, y, color))
        }
        fn region(
            &self,
            x: u16,
            y: u16,
            w: u16,
            h: u16,
        ) -> sails_rs::client::PendingCall<io::Region, Self::Env> {
            self.pending_call((x, y, w, h))
        }
        fn seq(&self) -> sails_rs::client::PendingCall<io::Seq, Self::Env> {
            self.pending_call(())
        }
        fn since(&self, from_seq: u64) -> sails_rs::client::PendingCall<io::Since, Self::Env> {
            self.pending_call((from_seq,))
        }
        fn snapshot(&self) -> sails_rs::client::PendingCall<io::Snapshot, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(CloseRoom () -> u64 | super::RoomError, 0, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Configure (config_blob: Vec<u8>) -> u64 | super::RoomError, 1, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Info () -> (String, u16, ActorId, u64, Vec<u8>, ), 2, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Join (name: String, kind: u16) -> u64 | super::RoomError, 3, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Leave () -> u64 | super::RoomError, 4, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Participants () -> Vec<(ActorId, String, u16, u64, )>, 5, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(PlacePixel (x: u16, y: u16, color: u16) -> u64 | super::RoomError, 6, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Region (x: u16, y: u16, w: u16, h: u16) -> Vec<u8> | super::RoomError, 7, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Seq () -> u64, 8, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Since (from_seq: u64) -> (u64, Vec<(u64, Vec<u8>, )>, bool, ), 9, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Snapshot () -> Vec<u8>, 10, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum RoomEvents {
            #[codec(index = 0)]
            Closed,
            #[codec(index = 1)]
            Configured(u64),
            #[codec(index = 2)]
            Joined([u8; 32]),
            #[codec(index = 3)]
            Left([u8; 32]),
            #[codec(index = 4)]
            PixelPlaced {
                x: u16,
                y: u16,
                color: u16,
                who: [u8; 32],
            },
            #[codec(index = 5)]
            Updated(u64),
        }

        impl RoomEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Closed { .. } => 0,
                    Self::Configured { .. } => 1,
                    Self::Joined { .. } => 2,
                    Self::Left { .. } => 3,
                    Self::PixelPlaced { .. } => 4,
                    Self::Updated { .. } => 5,
                }
            }
        }

        impl sails_rs::client::Event for RoomEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for RoomEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for RoomImpl {
            type Event = RoomEvents;
        }
    }
}
