// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct RoomFthClientProgram;

impl RoomFthClientProgram {
    pub const ROUTE_ID_ROOM: u8 = 1;
}

impl sails_rs::client::Program for RoomFthClientProgram {}

pub trait RoomFthClient {
    type Env: sails_rs::client::GearEnv;
    fn room(&self) -> sails_rs::client::Service<room::RoomImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> RoomFthClient
    for sails_rs::client::Actor<RoomFthClientProgram, E>
{
    type Env = E;
    fn room(&self) -> sails_rs::client::Service<room::RoomImpl, Self::Env> {
        self.service(RoomFthClientProgram::ROUTE_ID_ROOM)
    }
}
pub trait RoomFthClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
        reveal_tally_live: bool,
        reveal_timeout_secs: u64,
        round_count: u16,
        answer_max_bytes: u16,
    ) -> sails_rs::client::PendingCtor<RoomFthClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> RoomFthClientCtors
    for sails_rs::client::Deployment<RoomFthClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        reveal_tally_live: bool,
        reveal_timeout_secs: u64,
        round_count: u16,
        answer_max_bytes: u16,
    ) -> sails_rs::client::PendingCtor<RoomFthClientProgram, io::Create, Self::Env> {
        self.pending_ctor((
            reveal_tally_live,
            reveal_timeout_secs,
            round_count,
            answer_max_bytes,
        ))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (reveal_tally_live: bool, reveal_timeout_secs: u64, round_count: u16, answer_max_bytes: u16) -> (), 0);
}

pub mod room {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum RoomError {
        Closed,
        NotOwner,
        AlreadyJoined,
        NotJoined,
        AlreadySeated,
        SeatOccupied,
        NotAllowed,
        ParticipantsFull,
        NameTooLong { max_bytes: u16 },
        PayloadTooLarge { actual_bytes: u32, max_bytes: u16 },
        RateLimited { retry_after_secs: u32 },
        InvalidConfig,
        InvalidKind,
        InvalidBounds,
        InvalidColor,
        WrongPhase,
        AlreadyVoted,
        CommitMismatch,
        RevealTimeoutPending { remaining_secs: u32 },
        CooldownActive { retry_after_secs: u32 },
    }

    pub trait Room {
        type Env: sails_rs::client::GearEnv;
        fn abort_reveal(&mut self) -> sails_rs::client::PendingCall<io::AbortReveal, Self::Env>;
        fn cast_vote(
            &mut self,
            seat: u16,
        ) -> sails_rs::client::PendingCall<io::CastVote, Self::Env>;
        fn close_room(&mut self) -> sails_rs::client::PendingCall<io::CloseRoom, Self::Env>;
        fn configure(
            &mut self,
            config_blob: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::Configure, Self::Env>;
        fn game(&self) -> sails_rs::client::PendingCall<io::Game, Self::Env>;
        fn host_commit(
            &mut self,
            hash: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::HostCommit, Self::Env>;
        fn info(&self) -> sails_rs::client::PendingCall<io::Info, Self::Env>;
        fn join(
            &mut self,
            name: String,
            kind: u16,
        ) -> sails_rs::client::PendingCall<io::Join, Self::Env>;
        fn leave(&mut self) -> sails_rs::client::PendingCall<io::Leave, Self::Env>;
        fn open_voting(&mut self) -> sails_rs::client::PendingCall<io::OpenVoting, Self::Env>;
        fn participants(&self) -> sails_rs::client::PendingCall<io::Participants, Self::Env>;
        fn reveal(
            &mut self,
            seat: u16,
            salt: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::Reveal, Self::Env>;
        fn seq(&self) -> sails_rs::client::PendingCall<io::Seq, Self::Env>;
        fn since(&self, from_seq: u64) -> sails_rs::client::PendingCall<io::Since, Self::Env>;
        fn sit_down(&mut self, seat: u16) -> sails_rs::client::PendingCall<io::SitDown, Self::Env>;
        fn snapshot(&self) -> sails_rs::client::PendingCall<io::Snapshot, Self::Env>;
        fn start_round(
            &mut self,
            prompt: String,
        ) -> sails_rs::client::PendingCall<io::StartRound, Self::Env>;
        fn submit_answer(
            &mut self,
            text: String,
        ) -> sails_rs::client::PendingCall<io::SubmitAnswer, Self::Env>;
    }

    pub struct RoomImpl;

    impl sails_rs::client::Identifiable for RoomImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([233, 88, 222, 120, 147, 59, 28, 57]);
    }

    impl<E: sails_rs::client::GearEnv> Room for sails_rs::client::Service<RoomImpl, E> {
        type Env = E;
        fn abort_reveal(&mut self) -> sails_rs::client::PendingCall<io::AbortReveal, Self::Env> {
            self.pending_call(())
        }
        fn cast_vote(
            &mut self,
            seat: u16,
        ) -> sails_rs::client::PendingCall<io::CastVote, Self::Env> {
            self.pending_call((seat,))
        }
        fn close_room(&mut self) -> sails_rs::client::PendingCall<io::CloseRoom, Self::Env> {
            self.pending_call(())
        }
        fn configure(
            &mut self,
            config_blob: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::Configure, Self::Env> {
            self.pending_call((config_blob,))
        }
        fn game(&self) -> sails_rs::client::PendingCall<io::Game, Self::Env> {
            self.pending_call(())
        }
        fn host_commit(
            &mut self,
            hash: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::HostCommit, Self::Env> {
            self.pending_call((hash,))
        }
        fn info(&self) -> sails_rs::client::PendingCall<io::Info, Self::Env> {
            self.pending_call(())
        }
        fn join(
            &mut self,
            name: String,
            kind: u16,
        ) -> sails_rs::client::PendingCall<io::Join, Self::Env> {
            self.pending_call((name, kind))
        }
        fn leave(&mut self) -> sails_rs::client::PendingCall<io::Leave, Self::Env> {
            self.pending_call(())
        }
        fn open_voting(&mut self) -> sails_rs::client::PendingCall<io::OpenVoting, Self::Env> {
            self.pending_call(())
        }
        fn participants(&self) -> sails_rs::client::PendingCall<io::Participants, Self::Env> {
            self.pending_call(())
        }
        fn reveal(
            &mut self,
            seat: u16,
            salt: [u8; 32],
        ) -> sails_rs::client::PendingCall<io::Reveal, Self::Env> {
            self.pending_call((seat, salt))
        }
        fn seq(&self) -> sails_rs::client::PendingCall<io::Seq, Self::Env> {
            self.pending_call(())
        }
        fn since(&self, from_seq: u64) -> sails_rs::client::PendingCall<io::Since, Self::Env> {
            self.pending_call((from_seq,))
        }
        fn sit_down(&mut self, seat: u16) -> sails_rs::client::PendingCall<io::SitDown, Self::Env> {
            self.pending_call((seat,))
        }
        fn snapshot(&self) -> sails_rs::client::PendingCall<io::Snapshot, Self::Env> {
            self.pending_call(())
        }
        fn start_round(
            &mut self,
            prompt: String,
        ) -> sails_rs::client::PendingCall<io::StartRound, Self::Env> {
            self.pending_call((prompt,))
        }
        fn submit_answer(
            &mut self,
            text: String,
        ) -> sails_rs::client::PendingCall<io::SubmitAnswer, Self::Env> {
            self.pending_call((text,))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AbortReveal () -> u64 | super::RoomError, 0, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CastVote (seat: u16) -> u64 | super::RoomError, 1, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CloseRoom () -> u64 | super::RoomError, 2, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Configure (config_blob: Vec<u8>) -> u64 | super::RoomError, 3, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Game () -> ((bool, u64, u16, u16, bool, [u8; 32], u16, u16, bool, u16, bool, u64, ), (Vec<(u16, ActorId, )>, Vec<(u16, String, )>, Vec<(u16, u16, String, )>, Vec<(ActorId, u16, )>, Vec<u32>, ), ), 4, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(HostCommit (hash: [u8; 32]) -> u64 | super::RoomError, 5, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Info () -> (String, u16, ActorId, u64, Vec<u8>, ), 6, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Join (name: String, kind: u16) -> u64 | super::RoomError, 7, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Leave () -> u64 | super::RoomError, 8, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(OpenVoting () -> u64 | super::RoomError, 9, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Participants () -> Vec<(ActorId, String, u16, u64, )>, 10, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Reveal (seat: u16, salt: [u8; 32]) -> u64 | super::RoomError, 11, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Seq () -> u64, 12, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Since (from_seq: u64) -> (u64, Vec<(u64, Vec<u8>, )>, bool, ), 13, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SitDown (seat: u16) -> u64 | super::RoomError, 14, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Snapshot () -> Vec<u8>, 15, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(StartRound (prompt: String) -> u64 | super::RoomError, 16, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SubmitAnswer (text: String) -> u64 | super::RoomError, 17, <super::RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum RoomEvents {
            #[codec(index = 0)]
            AnswerSubmitted {
                round: u16,
                seat: u16,
                who: [u8; 32],
                text: String,
            },
            #[codec(index = 1)]
            Closed,
            #[codec(index = 2)]
            Configured(u64),
            #[codec(index = 3)]
            HostCommitted,
            #[codec(index = 4)]
            Joined([u8; 32]),
            #[codec(index = 5)]
            Left([u8; 32]),
            #[codec(index = 6)]
            RevealAborted,
            #[codec(index = 7)]
            Revealed { seat: u16 },
            #[codec(index = 8)]
            RoundStarted { round: u16, prompt: String },
            #[codec(index = 9)]
            SatDown { who: [u8; 32], seat: u16 },
            #[codec(index = 10)]
            Updated(u64),
            #[codec(index = 11)]
            VoteCast { who: [u8; 32], seat: u16 },
            #[codec(index = 12)]
            VotingOpened,
        }

        impl RoomEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::AnswerSubmitted { .. } => 0,
                    Self::Closed { .. } => 1,
                    Self::Configured { .. } => 2,
                    Self::HostCommitted { .. } => 3,
                    Self::Joined { .. } => 4,
                    Self::Left { .. } => 5,
                    Self::RevealAborted { .. } => 6,
                    Self::Revealed { .. } => 7,
                    Self::RoundStarted { .. } => 8,
                    Self::SatDown { .. } => 9,
                    Self::Updated { .. } => 10,
                    Self::VoteCast { .. } => 11,
                    Self::VotingOpened { .. } => 12,
                }
            }
        }

        impl sails_rs::client::Event for RoomEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for RoomEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <RoomImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for RoomImpl {
            type Event = RoomEvents;
        }
    }
}
